CREATE TABLE [dbo].[Client](
	[ID_Client] [int] IDENTITY(1,1) NOT NULL,
	[FIO] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Client] PRIMARY KEY CLUSTERED 
(
	[ID_Client] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Usluga](
	[ID_Usluga] [int] IDENTITY(1,1) NOT NULL,
	[Nazvanie] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Usluga] PRIMARY KEY CLUSTERED 
(
	[ID_Usluga] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Zayavka](
	[ID_Zayavka] [int] IDENTITY(1,1) NOT NULL,
	[Client_ID] [int] NOT NULL,
 CONSTRAINT [PK_Zayavka] PRIMARY KEY CLUSTERED 
(
	[ID_Zayavka] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[Zayavka]  WITH CHECK ADD  CONSTRAINT [FK_Zayavka_Client] FOREIGN KEY([Client_ID])
REFERENCES [dbo].[Client] ([ID_Client])
GO

ALTER TABLE [dbo].[Zayavka] CHECK CONSTRAINT [FK_Zayavka_Client]
GO

CREATE TABLE [dbo].[Zayavka_Usluga](
	[Zayavka_ID] [int] NOT NULL,
	[Usluga_ID] [int] NOT NULL,
 CONSTRAINT [PK_Zayavka_Usluga] PRIMARY KEY CLUSTERED 
(
	[Zayavka_ID] ASC,
	[Usluga_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[Zayavka_Usluga]  WITH CHECK ADD  CONSTRAINT [FK_Zayavka_Usluga_Usluga] FOREIGN KEY([Usluga_ID])
REFERENCES [dbo].[Usluga] ([ID_Usluga])
GO

ALTER TABLE [dbo].[Zayavka_Usluga] CHECK CONSTRAINT [FK_Zayavka_Usluga_Usluga]
GO

ALTER TABLE [dbo].[Zayavka_Usluga]  WITH CHECK ADD  CONSTRAINT [FK_Zayavka_Usluga_Zayavka] FOREIGN KEY([Zayavka_ID])
REFERENCES [dbo].[Zayavka] ([ID_Zayavka])
GO

ALTER TABLE [dbo].[Zayavka_Usluga] CHECK CONSTRAINT [FK_Zayavka_Usluga_Zayavka]
GO